; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
    -Iinclude
    -include include/User_Setup.h
    ; 修复 WebServer 库在 ESP32 Arduino core 3.x 下找不到头文件的问题
    -I C:/Users/57592/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
    -I C:/Users/57592/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
   

lib_deps = 
    bodmer/TFT_eSPI@^2.5.0
    paulstoffregen/XPT2046_Touchscreen
    bodmer/TJpg_Decoder@^1.0.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git

board_build.filesystem = littlefs  ; 关键：开启文件系统

; 指定上传和监视的串口（你的 ESP32 是 CH340，位于 COM5）
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200


